# Generated by Django 4.2.6 on 2023-10-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('bpId', models.IntegerField(null=True)),
                ('weightId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('recordIdW', models.AutoField(primary_key=True, serialize=False)),
                ('weightLb', models.DecimalField(decimal_places=1, max_digits=4)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserInfo.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('recordIdBp', models.AutoField(primary_key=True, serialize=False)),
                ('systolicPress', models.IntegerField(null=True)),
                ('diastolicPress', models.IntegerField(null=True)),
                ('bpm', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserInfo.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BloodGlucose',
            fields=[
                ('recordIdBg', models.AutoField(primary_key=True, serialize=False)),
                ('blood_sugar_level', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserInfo.patient')),
            ],
        ),
    ]
