# Generated by Django 4.2.6 on 2023-10-10 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('bpId', models.IntegerField(null=True)),
                ('weightId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightLb', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserInfo.user')),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolicPress', models.IntegerField(null=True)),
                ('diastolicPress', models.IntegerField(null=True)),
                ('bpm', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserInfo.user')),
            ],
        ),
    ]
