# Generated by Django 4.2.6 on 2023-10-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Patient',
        ),
        migrations.AlterField(
            model_name='weight',
            name='weightLb',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
