# Generated by Django 4.2.6 on 2023-10-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bpId',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weightId',
        ),
        migrations.AddField(
            model_name='patient',
            name='recordIdBg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserInfo.bloodglucose'),
        ),
        migrations.AddField(
            model_name='patient',
            name='recordIdBp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserInfo.bloodpressure'),
        ),
        migrations.AddField(
            model_name='patient',
            name='recordIdW',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserInfo.weight'),
        ),
    ]
