# Generated by Django 4.2.6 on 2023-10-11 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_rename_user_patient_alter_weight_weightlb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='userId',
            new_name='patientId',
        ),
    ]
